[package]
name = "veldr-common-systems"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
simd = ["vek/platform_intrinsics"]
plugins = ["common-state/plugins"]

default = ["simd"]

[dependencies]
common = { package = "veldr-common", path = ".." }
common-net = { package = "veldr-common-net", path = "../net" }
common-ecs = { package = "veldr-common-ecs", path = "../ecs" }
common-base = { package = "veldr-common-base", path = "../base" }

rand = { workspace = true }
rayon = { workspace = true }
tracing = { workspace = true }
vek = { workspace = true }
ordered-float = { workspace = true }
itertools = { workspace = true }

# ECS
specs = { workspace = true, features = [
    "serde",
    "storage-event-control",
    "derive",
] }

# Tweak running code
# inline_tweak = { workspace = true, features = ["release_tweak"] }

[dev-dependencies]
# Setup a State
common-state = { package = "veldr-common-state", path = "../state" }
