use crate::ui::img_ids::{BlankGraphic, ImageGraphic};

// TODO: Combine with image_ids, see macro definition
rotation_image_ids! {
    pub struct ImgsRot {
        <VoxelGraphic>

        <ImageGraphic>
        view_mmap: "veldr.element.ui.minimap.icons.mmap_view",
        indicator_mmap: "veldr.element.ui.minimap.icons.indicator_mmap",
        indicator_mmap_colored: "veldr.element.ui.minimap.icons.indicator_mmap_colored",
        // Tooltip Test
        tt_side: "veldr.element.ui.generic.frames.tt_test_edge",
        tt_corner: "veldr.element.ui.generic.frames.tt_test_corner_tr",
//////////////////////////////////////////////////////////////////////////////////////////////////////

    }
}

image_ids! {
    pub struct Imgs {
        <VoxelGraphic>
        // Missing: Buff Frame Animation .gif ?! we could do animation in ui.maintain, or in shader?

//////////////////////////////////////////////////////////////////////////////////////////////////////

        <ImageGraphic>

        // Checkboxes and Radio buttons
        check: "veldr.element.ui.generic.buttons.radio.inactive",
        check_mo: "veldr.element.ui.generic.buttons.radio.inactive_hover",
        check_press: "veldr.element.ui.generic.buttons.radio.press",
        check_checked: "veldr.element.ui.generic.buttons.radio.active",
        check_checked_mo: "veldr.element.ui.generic.buttons.radio.hover",
        checkbox: "veldr.element.ui.generic.buttons.checkbox.inactive",
        checkbox_mo: "veldr.element.ui.generic.buttons.checkbox.inactive_hover",
        checkbox_press: "veldr.element.ui.generic.buttons.checkbox.press",
        checkbox_checked: "veldr.element.ui.generic.buttons.checkbox.active",
        checkbox_checked_mo: "veldr.element.ui.generic.buttons.checkbox.hover",

        // Selection Frame
        selection: "veldr.element.ui.generic.frames.selection",
        selection_hover: "veldr.element.ui.generic.frames.selection_hover",
        selection_press: "veldr.element.ui.generic.frames.selection_press",

        // Prompt Dialog
        prompt_top: "veldr.element.ui.generic.frames.prompt_dialog_top",
        prompt_mid: "veldr.element.ui.generic.frames.prompt_dialog_mid",
        prompt_bot: "veldr.element.ui.generic.frames.prompt_dialog_bot",
        key_button: "veldr.element.ui.generic.buttons.key_button",
        key_button_press: "veldr.element.ui.generic.buttons.key_button_press",

        // Diary Window
        diary_bg: "veldr.element.ui.diary.diary_bg",
        diary_frame: "veldr.element.ui.diary.diary_frame",
        diary_exp_bg: "veldr.element.ui.diary.diary_exp_bg",
        diary_exp_frame: "veldr.element.ui.diary.diary_exp_frame",
        pixel: "veldr.element.ui.diary.pixel",
        arrow_l: "veldr.element.ui.diary.buttons.arrow_l",
        arrow_l_click: "veldr.element.ui.diary.buttons.arrow_l_click",
        arrow_l_inactive: "veldr.element.ui.diary.buttons.arrow_l_inactive",
        arrow_r: "veldr.element.ui.diary.buttons.arrow_r",
        arrow_r_click: "veldr.element.ui.diary.buttons.arrow_r_click",
        arrow_r_inactive: "veldr.element.ui.diary.buttons.arrow_r_inactive",
        ability_frame: "veldr.element.ui.diary.abilitiy_desc_frame",
        ability_frame_dual: "veldr.element.ui.diary.abilitiy_desc_frame_dual",
        sword_tree_paths: "veldr.element.ui.diary.sword_path_overlay",

        // Skill Trees
        book_bg: "veldr.element.ui.diary.spellbook_bg",
        skills_bg: "veldr.element.ui.diary.diary_skills_bg",
        slot_skills: "veldr.element.ui.diary.buttons.slot_skilltree",
        sword_bg: "veldr.element.ui.diary.sword_bg",
        axe_bg: "veldr.element.ui.diary.axe_bg",
        hammer_bg: "veldr.element.ui.diary.hammer_bg",
        bow_bg: "veldr.element.ui.diary.bow_bg",
        swords_crossed: "veldr.element.weapons.swords_crossed",
        sceptre: "veldr.element.weapons.sceptre",
        sword: "veldr.element.weapons.sword",
        axe: "veldr.element.weapons.axe",
        hammer: "veldr.element.weapons.hammer",
        bow: "veldr.element.weapons.bow",
        staff: "veldr.element.weapons.staff",
        mining: "veldr.element.weapons.mining",
        dig: "veldr.element.weapons.dig",
        pickaxe: "veldr.element.skills.pickaxe",
        pickaxe_ico: "veldr.element.weapons.pickaxe",
        skilltree_ico: "veldr.element.ui.diary.buttons.skilltree",
        spellbook_ico: "veldr.element.ui.diary.buttons.spellbook",
        spellbook_ico0: "veldr.element.ui.generic.buttons.spellbook0",
        stats_ico: "veldr.element.ui.diary.buttons.stats",
        crafting_ico: "veldr.element.ui.diary.buttons.crafting",
        lock: "veldr.element.ui.diary.buttons.lock",
        wpn_icon_border_skills: "veldr.element.ui.diary.buttons.border_skills",
        wpn_icon_border: "veldr.element.ui.generic.buttons.border",
        wpn_icon_border_mo: "veldr.element.ui.generic.buttons.border_mo",
        wpn_icon_border_press: "veldr.element.ui.generic.buttons.border_press",
        wpn_icon_border_pressed: "veldr.element.ui.generic.buttons.border_pressed",

        // Quest Window
        quest_bg: "veldr.element.ui.quests.quest_bg",
        quest_frame: "veldr.element.ui.quests.quest_frame",
        quest_ico: "veldr.element.ui.quests.quest_icon",

        // Social Window
        social_frame_on: "veldr.element.ui.social.social_frame",
        social_bg_on: "veldr.element.ui.social.social_bg",

        // Crafting Window
        crafting_window: "veldr.element.ui.crafting.crafting",
        crafting_frame: "veldr.element.ui.crafting.crafting_frame",
        crafting_icon_bordered: "veldr.element.ui.generic.buttons.anvil",
        crafting_icon: "veldr.element.ui.generic.buttons.anvil",
        crafting_icon_hover: "veldr.element.ui.generic.buttons.anvil_hover",
        crafting_icon_press: "veldr.element.ui.generic.buttons.anvil_press",
        quality_indicator: "veldr.element.ui.crafting.quality_indicator",
        icon_claw: "veldr.element.ui.crafting.icons.claw",
        icon_ingot: "veldr.element.ui.crafting.icons.ingot",
        icon_log: "veldr.element.ui.crafting.icons.log",
        icon_armor: "veldr.element.ui.crafting.icons.armors",
        icon_tools: "veldr.element.ui.crafting.icons.crafting_tools",
        icon_dismantle: "veldr.element.ui.crafting.icons.dismantle",
        icon_food: "veldr.element.ui.crafting.icons.foods",
        icon_glider: "veldr.element.ui.crafting.icons.gliders",
        icon_globe: "veldr.element.ui.crafting.icons.globe",
        icon_potion: "veldr.element.ui.crafting.icons.potions",
        icon_utility: "veldr.element.ui.crafting.icons.utilities",
        icon_weapon: "veldr.element.ui.crafting.icons.weapons",
        icon_bag: "veldr.element.items.item_bag_leather_large",
        icon_processed_material: "veldr.element.ui.crafting.icons.processed_material",
        crafting_modular_art: "veldr.element.ui.crafting.modular_weps_art",
        icon_primary_comp: "veldr.element.ui.crafting.icons.blade",
        icon_secondary_comp: "veldr.element.ui.crafting.icons.handle",
        icon_mod_weap: "veldr.element.ui.bag.backgrounds.mainhand",
        // Group Window
        member_frame: "veldr.element.ui.groups.group_member_frame",
        member_bg: "veldr.element.ui.groups.group_member_bg",

        // Chat-Arrows
        chat_arrow: "veldr.element.ui.generic.buttons.arrow_down",
        chat_arrow_mo: "veldr.element.ui.generic.buttons.arrow_down_hover",
        chat_arrow_press: "veldr.element.ui.generic.buttons.arrow_down_press",

        // Settings Window
        settings_button: "veldr.element.ui.settings.buttons.settings_button",
        settings_button_pressed: "veldr.element.ui.settings.buttons.settings_button_pressed",
        settings_button_hover: "veldr.element.ui.settings.buttons.settings_button_hover",
        settings_button_press: "veldr.element.ui.settings.buttons.settings_button_press",

        settings_plus: "veldr.element.ui.settings.buttons.settings_button_plus",
        settings_plus_hover: "veldr.element.ui.settings.buttons.settings_button_plus_hover",
        settings_plus_press: "veldr.element.ui.settings.buttons.settings_button_plus_press",

        chat_tab_settings_bg: "veldr.element.ui.settings.chat_tab_settings_bg",
        chat_tab_settings_frame: "veldr.element.ui.settings.chat_tab_settings_frame",

        quest_bg0: "veldr.element.ui.quests.temp_quest_bg",

        // Slider
        slider: "veldr.element.ui.generic.slider.track",
        slider_indicator: "veldr.element.ui.generic.slider.indicator",
        slider_indicator_small: "veldr.element.ui.generic.slider.indicator_round",

        // Buttons
        settings: "veldr.element.ui.generic.buttons.settings",
        settings_hover: "veldr.element.ui.generic.buttons.settings_hover",
        settings_press: "veldr.element.ui.generic.buttons.settings_press",

        social: "veldr.element.ui.generic.buttons.social",
        social_hover: "veldr.element.ui.generic.buttons.social_hover",
        social_press: "veldr.element.ui.generic.buttons.social_press",
        player_pvp: "veldr.element.ui.social.player_pvp",
        pvp_on: "veldr.element.ui.social.pvp_on",
        pvp_off: "veldr.element.ui.social.pvp_off",

        map_button: "veldr.element.ui.generic.buttons.map",
        map_hover: "veldr.element.ui.generic.buttons.map_hover",
        map_press: "veldr.element.ui.generic.buttons.map_press",

        spellbook_button: "veldr.element.ui.generic.buttons.spellbook",
        spellbook_hover: "veldr.element.ui.generic.buttons.spellbook_hover",
        spellbook_press: "veldr.element.ui.generic.buttons.spellbook_press",

        group_icon: "veldr.element.ui.generic.buttons.group",
        group_icon_hover: "veldr.element.ui.generic.buttons.group_hover",
        group_icon_press: "veldr.element.ui.generic.buttons.group_press",

        sp_indicator_arrow: "veldr.element.ui.generic.buttons.arrow_down_gold",

        // Controller Buttons/Icons
        south_button_a: "veldr.element.ui.generic.controller.south_button_a",
        south_button_ps_cross: "veldr.element.ui.generic.controller.south_button_ps_cross",
        east_button_b: "veldr.element.ui.generic.controller.east_button_b",
        east_button_ps_circle: "veldr.element.ui.generic.controller.east_button_ps_circle",
        west_button_x: "veldr.element.ui.generic.controller.west_button_x",
        west_button_ps_square: "veldr.element.ui.generic.controller.west_button_ps_square",
        north_button_y: "veldr.element.ui.generic.controller.north_button_y",
        north_button_ps_triangle: "veldr.element.ui.generic.controller.north_button_ps_triangle",

        left_axis: "veldr.element.ui.generic.controller.left_axis_l",
        left_axis_button: "veldr.element.ui.generic.controller.left_axis_button_lb",
        right_axis: "veldr.element.ui.generic.controller.right_axis_r",
        right_axis_button: "veldr.element.ui.generic.controller.right_axis_button_rb",

        left_shoulder_xbox_lb: "veldr.element.ui.generic.controller.left_shoulder_xbox_lb",
        left_shoulder_nin_l: "veldr.element.ui.generic.controller.left_shoulder_nin_l",
        left_shoulder_ps_l1: "veldr.element.ui.generic.controller.left_shoulder_ps_l1",
        right_shoulder_xbox_rb: "veldr.element.ui.generic.controller.right_shoulder_xbox_rb",
        right_shoulder_nin_r: "veldr.element.ui.generic.controller.right_shoulder_nin_r",
        right_shoulder_ps_r1: "veldr.element.ui.generic.controller.right_shoulder_ps_r1",

        left_trigger_xbox_lt: "veldr.element.ui.generic.controller.left_trigger_xbox_lt",
        left_trigger_nin_zl: "veldr.element.ui.generic.controller.left_trigger_nin_zl",
        left_trigger_ps_l2: "veldr.element.ui.generic.controller.left_trigger_ps_l2",
        right_trigger_xbox_rt: "veldr.element.ui.generic.controller.right_trigger_xbox_rt",
        right_trigger_nin_zr: "veldr.element.ui.generic.controller.right_trigger_nin_zr",
        right_trigger_ps_r2: "veldr.element.ui.generic.controller.right_trigger_ps_r2",

        dpad_down: "veldr.element.ui.generic.controller.dpad_down",
        dpad_down_ps: "veldr.element.ui.generic.controller.dpad_down_ps",
        dpad_left: "veldr.element.ui.generic.controller.dpad_left",
        dpad_left_ps: "veldr.element.ui.generic.controller.dpad_left_ps",
        dpad_right: "veldr.element.ui.generic.controller.dpad_right",
        dpad_right_ps: "veldr.element.ui.generic.controller.dpad_right_ps",
        dpad_up: "veldr.element.ui.generic.controller.dpad_up",
        dpad_up_ps: "veldr.element.ui.generic.controller.dpad_up_ps",

        start_button_xbox: "veldr.element.ui.generic.controller.start_button_xbox",
        start_button_nin: "veldr.element.ui.generic.controller.start_button_nin_+",
        start_button_ps: "veldr.element.ui.generic.controller.start_button_ps",
        select_button_xbox: "veldr.element.ui.generic.controller.select_button_xbox",
        select_button_nin: "veldr.element.ui.generic.controller.select_button_nin_-",
        select_button_ps: "veldr.element.ui.generic.controller.select_button_ps",

        no_button: "veldr.element.ui.generic.controller.no_button_warning",
        transparant_button: "veldr.element.ui.generic.controller.transparant_icon",

        // Controller dark outlines for skillbar
        left_trigger_xbox_dark: "veldr.element.ui.generic.controller.left_trigger_xbox_lt_dark",
        left_trigger_nin_dark: "veldr.element.ui.generic.controller.left_trigger_nin_zl_dark",
        left_trigger_ps_dark: "veldr.element.ui.generic.controller.left_trigger_ps_l2_dark",
        right_trigger_xbox_dark: "veldr.element.ui.generic.controller.right_trigger_xbox_rt_dark",
        right_trigger_nin_dark: "veldr.element.ui.generic.controller.right_trigger_nin_zr_dark",
        right_trigger_ps_dark: "veldr.element.ui.generic.controller.right_trigger_ps_r2_dark",

        // Skill Icons
        onehdagger_m1: "veldr.element.weapons.daggers",
        onehdagger_m2: "veldr.element.skills.skill_slice_2",
        onehshield_m1: "veldr.element.weapons.swordshield",
        onehshield_m2: "veldr.element.weapons.swordshield",
        staff_melee: "veldr.element.skills.staff_m1",
        fireball: "veldr.element.skills.staff_m2",
        flyingrod_m1: "veldr.element.skills.debug_wand_m1",
        flyingrod_m2: "veldr.element.skills.debug_wand_m2",
        fire_aoe: "veldr.element.skills.skill_fire_aoe",
        flamethrower: "veldr.element.skills.skill_flamethrower",
        // Sword
        sword_heavy_stance: "veldr.element.skills.sword.heavy_stance",
        sword_agile_stance: "veldr.element.skills.sword.agile_stance",
        sword_defensive_stance: "veldr.element.skills.sword.defensive_stance",
        sword_crippling_stance: "veldr.element.skills.sword.crippling_stance",
        sword_cleaving_stance: "veldr.element.skills.sword.cleaving_stance",
        sword_double_slash: "veldr.element.skills.sword.basic_double_slash",
        sword_basic_double_slash: "veldr.element.skills.sword.basic_double_slash",
        sword_heavy_double_slash: "veldr.element.skills.sword.heavy_double_slash",
        sword_agile_double_slash: "veldr.element.skills.sword.agile_double_slash",
        sword_defensive_double_slash: "veldr.element.skills.sword.defensive_double_slash",
        sword_crippling_double_slash: "veldr.element.skills.sword.crippling_double_slash",
        sword_cleaving_double_slash: "veldr.element.skills.sword.cleaving_double_slash",
        sword_secondary_ability: "veldr.element.skills.sword.secondary_ability",
        sword_basic_thrust: "veldr.element.skills.sword.basic_thrust",
        sword_heavy_slam: "veldr.element.skills.sword.heavy_slam",
        sword_agile_perforate: "veldr.element.skills.sword.agile_perforate",
        sword_defensive_vital_jab: "veldr.element.skills.sword.defensive_vital_jab",
        sword_crippling_deep_rend: "veldr.element.skills.sword.crippling_deep_rend",
        sword_cleaving_spiral_slash: "veldr.element.skills.sword.cleaving_spiral_slash",
        sword_crescent_slash: "veldr.element.skills.sword.crescent_slash",
        sword_basic_crescent_slash: "veldr.element.skills.sword.crescent_slash",
        sword_heavy_crescent_slash: "veldr.element.skills.sword.heavy_crescent_slash",
        sword_agile_crescent_slash: "veldr.element.skills.sword.agile_crescent_slash",
        sword_defensive_crescent_slash: "veldr.element.skills.sword.defensive_crescent_slash",
        sword_crippling_crescent_slash: "veldr.element.skills.sword.crippling_crescent_slash",
        sword_cleaving_crescent_slash: "veldr.element.skills.sword.cleaving_crescent_slash",
        sword_fell_strike: "veldr.element.skills.sword.fell_strike",
        sword_basic_fell_strike: "veldr.element.skills.sword.fell_strike",
        sword_heavy_fell_strike: "veldr.element.skills.sword.heavy_fell_strike",
        sword_agile_fell_strike: "veldr.element.skills.sword.agile_fell_strike",
        sword_defensive_fell_strike: "veldr.element.skills.sword.defensive_fell_strike",
        sword_crippling_fell_strike: "veldr.element.skills.sword.crippling_fell_strike",
        sword_cleaving_fell_strike: "veldr.element.skills.sword.cleaving_fell_strike",
        sword_skewer: "veldr.element.skills.sword.skewer",
        sword_basic_skewer: "veldr.element.skills.sword.skewer",
        sword_heavy_skewer: "veldr.element.skills.sword.heavy_skewer",
        sword_agile_skewer: "veldr.element.skills.sword.agile_skewer",
        sword_defensive_skewer: "veldr.element.skills.sword.defensive_skewer",
        sword_crippling_skewer: "veldr.element.skills.sword.crippling_skewer",
        sword_cleaving_skewer: "veldr.element.skills.sword.cleaving_skewer",
        sword_cascade: "veldr.element.skills.sword.cascade",
        sword_basic_cascade: "veldr.element.skills.sword.cascade",
        sword_heavy_cascade: "veldr.element.skills.sword.heavy_cascade",
        sword_agile_cascade: "veldr.element.skills.sword.agile_cascade",
        sword_defensive_cascade: "veldr.element.skills.sword.defensive_cascade",
        sword_crippling_cascade: "veldr.element.skills.sword.crippling_cascade",
        sword_cleaving_cascade: "veldr.element.skills.sword.cleaving_cascade",
        sword_cross_cut: "veldr.element.skills.sword.cross_cut",
        sword_basic_cross_cut: "veldr.element.skills.sword.cross_cut",
        sword_heavy_cross_cut: "veldr.element.skills.sword.heavy_cross_cut",
        sword_agile_cross_cut: "veldr.element.skills.sword.agile_cross_cut",
        sword_defensive_cross_cut: "veldr.element.skills.sword.defensive_cross_cut",
        sword_crippling_cross_cut: "veldr.element.skills.sword.crippling_cross_cut",
        sword_cleaving_cross_cut: "veldr.element.skills.sword.cleaving_cross_cut",
        sword_finisher: "veldr.element.skills.sword.finisher",
        sword_basic_mighty_strike: "veldr.element.skills.sword.basic_mighty_strike",
        sword_heavy_guillotine: "veldr.element.skills.sword.heavy_guillotine",
        sword_agile_hundred_cuts: "veldr.element.skills.sword.agile_hundred_cuts",
        sword_defensive_counter: "veldr.element.skills.sword.defensive_counter",
        sword_crippling_mutilate: "veldr.element.skills.sword.crippling_mutilate",
        sword_cleaving_bladestorm: "veldr.element.skills.sword.cleaving_bladestorm",
        sword_heavy_sweep: "veldr.element.skills.sword.heavy_sweep",
        sword_heavy_pommel_strike: "veldr.element.skills.sword.heavy_pommel_strike",
        sword_agile_quick_draw: "veldr.element.skills.sword.agile_quick_draw",
        sword_agile_feint: "veldr.element.skills.sword.agile_feint",
        sword_defensive_riposte: "veldr.element.skills.sword.defensive_riposte",
        sword_defensive_disengage: "veldr.element.skills.sword.defensive_disengage",
        sword_crippling_gouge: "veldr.element.skills.sword.crippling_gouge",
        sword_crippling_hamstring: "veldr.element.skills.sword.crippling_hamstring",
        sword_cleaving_whirlwind_slice: "veldr.element.skills.sword.cleaving_whirlwind_slice",
        sword_cleaving_earth_splitter: "veldr.element.skills.sword.cleaving_earth_splitter",
        sword_heavy_fortitude: "veldr.element.skills.sword.heavy_fortitude",
        sword_heavy_pillar_thrust: "veldr.element.skills.sword.heavy_pillar_thrust",
        sword_agile_dancing_edge: "veldr.element.skills.sword.agile_dancing_edge",
        sword_agile_flurry: "veldr.element.skills.sword.agile_flurry",
        sword_defensive_stalwart_sword: "veldr.element.skills.sword.defensive_stalwart_sword",
        sword_defensive_deflect: "veldr.element.skills.sword.defensive_deflect",
        sword_crippling_eviscerate: "veldr.element.skills.sword.crippling_eviscerate",
        sword_crippling_bloody_gash: "veldr.element.skills.sword.crippling_bloody_gash",
        sword_cleaving_blade_fever: "veldr.element.skills.sword.cleaving_blade_fever",
        sword_cleaving_sky_splitter: "veldr.element.skills.sword.cleaving_sky_splitter",
        // Axe
        axe_triple_chop: "veldr.element.skills.axe.triple_chop",
        axe_cleave: "veldr.element.skills.axe.cleave",
        axe_brutal_swing: "veldr.element.skills.axe.brutal_swing",
        axe_berserk: "veldr.element.skills.axe.berserk",
        axe_rising_tide: "veldr.element.skills.axe.rising_tide",
        axe_savage_sense: "veldr.element.skills.axe.savage_sense",
        axe_adrenaline_rush: "veldr.element.skills.axe.adrenaline_rush",
        axe_execute: "veldr.element.skills.axe.execute",
        axe_maelstrom: "veldr.element.skills.axe.maelstrom",
        axe_rake: "veldr.element.skills.axe.rake",
        axe_bloodfeast: "veldr.element.skills.axe.bloodfeast",
        axe_fierce_raze: "veldr.element.skills.axe.fierce_raze",
        axe_furor: "veldr.element.skills.axe.furor",
        axe_fracture: "veldr.element.skills.axe.fracture",
        axe_lacerate: "veldr.element.skills.axe.lacerate",
        axe_riptide: "veldr.element.skills.axe.riptide",
        axe_skull_bash: "veldr.element.skills.axe.skull_bash",
        axe_sunder: "veldr.element.skills.axe.sunder",
        axe_plunder: "veldr.element.skills.axe.plunder",
        axe_defiance: "veldr.element.skills.axe.defiance",
        axe_keelhaul: "veldr.element.skills.axe.keelhaul",
        axe_bulkhead: "veldr.element.skills.axe.bulkhead",
        axe_capsize: "veldr.element.skills.axe.capsize",
        // Hammer
        hammer_solid_smash: "veldr.element.skills.hammer.solid_smash",
        hammer_wide_wallop: "veldr.element.skills.hammer.wide_wallop",
        hammer_scornful_swipe: "veldr.element.skills.hammer.scornful_swipe",
        hammer_tremor: "veldr.element.skills.hammer.tremor",
        hammer_vigorous_bash: "veldr.element.skills.hammer.vigorous_bash",
        hammer_heavy_whorl: "veldr.element.skills.hammer.heavy_whorl",
        hammer_intercept: "veldr.element.skills.hammer.intercept",
        hammer_retaliate: "veldr.element.skills.hammer.retaliate",
        hammer_spine_cracker: "veldr.element.skills.hammer.spine_cracker",
        hammer_breach: "veldr.element.skills.hammer.breach",
        hammer_pile_driver: "veldr.element.skills.hammer.pile_driver",
        hammer_lung_pummel: "veldr.element.skills.hammer.lung_pummel",
        hammer_helm_crusher: "veldr.element.skills.hammer.helm_crusher",
        hammer_iron_tempest: "veldr.element.skills.hammer.iron_tempest",
        hammer_upheaval: "veldr.element.skills.hammer.upheaval",
        hammer_rampart: "veldr.element.skills.hammer.rampart",
        hammer_tenacity: "veldr.element.skills.hammer.tenacity",
        hammer_thunderclap: "veldr.element.skills.hammer.thunderclap",
        hammer_seismic_shock: "veldr.element.skills.hammer.seismic_shock",
        hammer_earthshaker: "veldr.element.skills.hammer.earthshaker",
        hammer_judgement: "veldr.element.skills.hammer.judgement",
        // Bow
        bow_arrow_shot: "veldr.element.skills.bow.arrow_shot",
        bow_broadhead: "veldr.element.skills.bow.broadhead",
        bow_foothold: "veldr.element.skills.bow.foothold",
        bow_heavy_nock: "veldr.element.skills.bow.heavy_nock",
        bow_ardent_hunt: "veldr.element.skills.bow.ardent_hunt",
        bow_owl_talon: "veldr.element.skills.bow.owl_talon",
        bow_eagle_eye: "veldr.element.skills.bow.eagle_eye",
        bow_heartseeker: "veldr.element.skills.bow.heartseeker",
        bow_hawkstrike: "veldr.element.skills.bow.hawkstrike",
        bow_septic_shot: "veldr.element.skills.bow.septic_shot",
        bow_ignite_arrow: "veldr.element.skills.bow.ignite_arrow",
        bow_burning_arrow: "veldr.element.skills.bow.burning_arrow",
        bow_burning_broadhead: "veldr.element.skills.bow.burning_broadhead",
        bow_drench_arrow: "veldr.element.skills.bow.drench_arrow",
        bow_poison_arrow: "veldr.element.skills.bow.poison_arrow",
        bow_poison_broadhead: "veldr.element.skills.bow.poison_broadhead",
        bow_freeze_arrow: "veldr.element.skills.bow.freeze_arrow",
        bow_freezing_arrow: "veldr.element.skills.bow.freezing_arrow",
        bow_freezing_broadhead: "veldr.element.skills.bow.freezing_broadhead",
        bow_jolt_arrow: "veldr.element.skills.bow.jolt_arrow",
        bow_lightning_arrow: "veldr.element.skills.bow.lightning_arrow",
        bow_lightning_broadhead: "veldr.element.skills.bow.lightning_broadhead",
        bow_barrage: "veldr.element.skills.bow.barrage",
        bow_piercing_gale: "veldr.element.skills.bow.piercing_gale",
        bow_scatterburst: "veldr.element.skills.bow.scatterburst",
        bow_lesser_scatterburst: "veldr.element.skills.bow.lesser_scatterburst",
        bow_greater_scatterburst: "veldr.element.skills.bow.greater_scatterburst",
        bow_fusillade: "veldr.element.skills.bow.fusillade",
        bow_death_volley: "veldr.element.skills.bow.death_volley",
        // Skilltree Icons
        health_plus_skill: "veldr.element.skills.skilltree.health_plus",
        energy_plus_skill: "veldr.element.skills.skilltree.energy_plus",
        unlock_axe_skill: "veldr.element.skills.skilltree.unlock_axe",
        unlock_bow_skill: "veldr.element.skills.skilltree.unlock_bow",
        unlock_hammer_skill: "veldr.element.skills.skilltree.unlock_hammer",
        unlock_sceptre_skill: "veldr.element.skills.skilltree.unlock_sceptre",
        unlock_staff_skill0: "veldr.element.skills.skilltree.unlock_staff-0",
        unlock_sword_skill: "veldr.element.skills.skilltree.unlock_sword",
        skill_dodge_skill: "veldr.element.skills.skilltree.skill_dodge",
        skill_climbing_skill: "veldr.element.skills.skilltree.skill_climbing",
        skill_swim_skill: "veldr.element.skills.skilltree.skill_swim",

        buff_amount_skill: "veldr.element.skills.skilltree.buff_amount",
        buff_combo_skill: "veldr.element.skills.skilltree.buff_combo",
        buff_cost_skill: "veldr.element.skills.skilltree.buff_cost",
        buff_damage_skill: "veldr.element.skills.skilltree.buff_damage",
        buff_distance_skill: "veldr.element.skills.skilltree.buff_distance",
        buff_energy_drain_skill: "veldr.element.skills.skilltree.buff_energy_drain",
        buff_energy_regen_skill: "veldr.element.skills.skilltree.buff_energy_regen",
        buff_explosion_skill: "veldr.element.skills.skilltree.buff_explosion",
        buff_heal_skill: "veldr.element.skills.skilltree.buff_heal",
        buff_helicopter_skill: "veldr.element.skills.skilltree.buff_helicopter",
        buff_infinite_skill: "veldr.element.skills.skilltree.buff_infinite",
        buff_knockback_skill: "veldr.element.skills.skilltree.buff_knockback",
        buff_lifesteal_skill: "veldr.element.skills.skilltree.buff_lifesteal",
        buff_projectile_speed_skill: "veldr.element.skills.skilltree.buff_projectile_speed",
        buff_radius_skill: "veldr.element.skills.skilltree.buff_radius",
        buff_speed_skill: "veldr.element.skills.skilltree.buff_speed",
        buff_duration_skill: "veldr.element.skills.skilltree.buff_duration",

        debuff_amount_skill: "veldr.element.skills.skilltree.debuff_amount",
        debuff_combo_skill: "veldr.element.skills.skilltree.debuff_combo",
        debuff_cost_skill: "veldr.element.skills.skilltree.debuff_cost",
        debuff_damage_skill: "veldr.element.skills.skilltree.debuff_damage",
        debuff_distance_skill: "veldr.element.skills.skilltree.debuff_distance",
        debuff_energy_drain_skill: "veldr.element.skills.skilltree.debuff_energy_drain",
        debuff_energy_regen_skill: "veldr.element.skills.skilltree.debuff_energy_regen",
        debuff_explosion_skill: "veldr.element.skills.skilltree.debuff_explosion",
        debuff_heal_skill: "veldr.element.skills.skilltree.debuff_heal",
        debuff_helicopter_skill: "veldr.element.skills.skilltree.debuff_helicopter",
        debuff_infinite_skill: "veldr.element.skills.skilltree.debuff_infinite",
        debuff_knockback_skill: "veldr.element.skills.skilltree.debuff_knockback",
        debuff_lifesteal_skill: "veldr.element.skills.skilltree.debuff_lifesteal",
        debuff_projectile_speed_skill: "veldr.element.skills.skilltree.debuff_projectile_speed",
        debuff_radius_skill: "veldr.element.skills.skilltree.debuff_radius",
        debuff_speed_skill: "veldr.element.skills.skilltree.debuff_speed",
        debuff_duration_skill: "veldr.element.skills.skilltree.debuff_duration",

        heal_amount_skill: "veldr.element.skills.skilltree.heal_amount",
        heal_combo_skill: "veldr.element.skills.skilltree.heal_combo",
        heal_cost_skill: "veldr.element.skills.skilltree.heal_cost",
        heal_damage_skill: "veldr.element.skills.skilltree.heal_damage",
        heal_distance_skill: "veldr.element.skills.skilltree.heal_distance",
        heal_energy_drain_skill: "veldr.element.skills.skilltree.heal_energy_drain",
        heal_energy_regen_skill: "veldr.element.skills.skilltree.heal_energy_regen",
        heal_explosion_skill: "veldr.element.skills.skilltree.heal_explosion",
        heal_heal_skill: "veldr.element.skills.skilltree.heal_heal",
        heal_helicopter_skill: "veldr.element.skills.skilltree.heal_helicopter",
        heal_infinite_skill: "veldr.element.skills.skilltree.heal_infinite",
        heal_knockback_skill: "veldr.element.skills.skilltree.heal_knockback",
        heal_lifesteal_skill: "veldr.element.skills.skilltree.heal_lifesteal",
        heal_projectile_speed_skill: "veldr.element.skills.skilltree.heal_projectile_speed",
        heal_radius_skill: "veldr.element.skills.skilltree.heal_radius",
        heal_speed_skill: "veldr.element.skills.skilltree.heal_speed",
        heal_duration_skill: "veldr.element.skills.skilltree.heal_duration",

        magic_amount_skill: "veldr.element.skills.skilltree.magic_amount",
        magic_combo_skill: "veldr.element.skills.skilltree.magic_combo",
        magic_cost_skill: "veldr.element.skills.skilltree.magic_cost",
        magic_damage_skill: "veldr.element.skills.skilltree.magic_damage",
        magic_distance_skill: "veldr.element.skills.skilltree.magic_distance",
        magic_energy_drain_skill: "veldr.element.skills.skilltree.magic_energy_drain",
        magic_energy_regen_skill: "veldr.element.skills.skilltree.magic_energy_regen",
        magic_explosion_skill: "veldr.element.skills.skilltree.magic_explosion",
        magic_heal_skill: "veldr.element.skills.skilltree.magic_heal",
        magic_helicopter_skill: "veldr.element.skills.skilltree.magic_helicopter",
        magic_infinite_skill: "veldr.element.skills.skilltree.magic_infinite",
        magic_knockback_skill: "veldr.element.skills.skilltree.magic_knockback",
        magic_lifesteal_skill: "veldr.element.skills.skilltree.magic_lifesteal",
        magic_projectile_speed_skill: "veldr.element.skills.skilltree.magic_projectile_speed",
        magic_radius_skill: "veldr.element.skills.skilltree.magic_radius",
        magic_speed_skill: "veldr.element.skills.skilltree.magic_speed",
        magic_duration_skill: "veldr.element.skills.skilltree.magic_duration",

        physical_amount_skill: "veldr.element.skills.skilltree.physical_amount",
        physical_combo_skill: "veldr.element.skills.skilltree.physical_combo",
        physical_cost_skill: "veldr.element.skills.skilltree.physical_cost",
        physical_damage_skill: "veldr.element.skills.skilltree.physical_damage",
        physical_distance_skill: "veldr.element.skills.skilltree.physical_distance",
        physical_energy_drain_skill: "veldr.element.skills.skilltree.physical_energy_drain",
        physical_energy_regen_skill: "veldr.element.skills.skilltree.physical_energy_regen",
        physical_explosion_skill: "veldr.element.skills.skilltree.physical_explosion",
        physical_heal_skill: "veldr.element.skills.skilltree.physical_heal",
        physical_helicopter_skill: "veldr.element.skills.skilltree.physical_helicopter",
        physical_infinite_skill: "veldr.element.skills.skilltree.physical_infinite",
        physical_knockback_skill: "veldr.element.skills.skilltree.physical_knockback",
        physical_lifesteal_skill: "veldr.element.skills.skilltree.physical_lifesteal",
        physical_projectile_speed_skill: "veldr.element.skills.skilltree.physical_projectile_speed",
        physical_radius_skill: "veldr.element.skills.skilltree.physical_radius",
        physical_speed_skill: "veldr.element.skills.skilltree.physical_speed",
        physical_duration_skill: "veldr.element.skills.skilltree.physical_duration",

        utility_amount_skill: "veldr.element.skills.skilltree.utility_amount",
        utility_combo_skill: "veldr.element.skills.skilltree.utility_combo",
        utility_cost_skill: "veldr.element.skills.skilltree.utility_cost",
        utility_damage_skill: "veldr.element.skills.skilltree.utility_damage",
        utility_distance_skill: "veldr.element.skills.skilltree.utility_distance",
        utility_energy_drain_skill: "veldr.element.skills.skilltree.utility_energy_drain",
        utility_energy_regen_skill: "veldr.element.skills.skilltree.utility_energy_regen",
        utility_explosion_skill: "veldr.element.skills.skilltree.utility_explosion",
        utility_heal_skill: "veldr.element.skills.skilltree.utility_heal",
        utility_helicopter_skill: "veldr.element.skills.skilltree.utility_helicopter",
        utility_infinite_skill: "veldr.element.skills.skilltree.utility_infinite",
        utility_knockback_skill: "veldr.element.skills.skilltree.utility_knockback",
        utility_lifesteal_skill: "veldr.element.skills.skilltree.utility_lifesteal",
        utility_projectile_speed_skill: "veldr.element.skills.skilltree.utility_projectile_speed",
        utility_radius_skill: "veldr.element.skills.skilltree.utility_radius",
        utility_speed_skill: "veldr.element.skills.skilltree.utility_speed",
        utility_duration_skill: "veldr.element.skills.skilltree.utility_duration",

        pickaxe_speed_skill: "veldr.element.skills.pickaxe_speed",
        pickaxe_oregain_skill: "veldr.element.skills.pickaxe_oregain",
        pickaxe_gemgain_skill: "veldr.element.skills.pickaxe_gemgain",

        // Skillbar
        level_up: "veldr.element.ui.skillbar.level_up",
        bar_content: "veldr.element.ui.skillbar.bar_content",
        skillbar_bg: "veldr.element.ui.skillbar.bg",
        skillbar_frame: "veldr.element.ui.skillbar.frame",
        health_bg: "veldr.element.ui.skillbar.health_bg",
        health_frame: "veldr.element.ui.skillbar.health_frame",
        exp_frame: "veldr.element.ui.skillbar.exp_frame",
        exp_frame_bg: "veldr.element.ui.skillbar.exp_frame_bg",
        selected_exp: "veldr.element.ui.skillbar.selected_exp_frame",
        bag_frame: "veldr.element.ui.skillbar.bag_frame",
        selected_exp_bg: "veldr.element.ui.skillbar.selected_exp_frame_bg",
        decayed_bg: "veldr.element.ui.skillbar.decayed_bg",
        energy_bg: "veldr.element.ui.skillbar.energy_bg",
        energy_frame: "veldr.element.ui.skillbar.energy_frame",
        poise_bg: "veldr.element.ui.skillbar.poise_bg",
        poise_frame: "veldr.element.ui.skillbar.poise_frame",
        poise_tick: "veldr.element.ui.skillbar.bar_content",
        m1_ico: "veldr.element.ui.generic.icons.m1",
        m2_ico: "veldr.element.ui.generic.icons.m2",
        m_scroll_ico: "veldr.element.ui.generic.icons.m_scroll",
        m_move_ico: "veldr.element.ui.generic.icons.m_move",
        m_click_ico: "veldr.element.ui.generic.icons.m_click",
        skillbar_slot: "veldr.element.ui.skillbar.slot",
        bag_ico: "veldr.element.ui.generic.buttons.bag",
        skillbar_index: "veldr.element.ui.generic.buttons.hotbar_index",

        // Other Icons/Art
        hardcore: "veldr.element.ui.map.icons.dif_map_icon",
        skull: "veldr.element.ui.generic.icons.skull",
        skull_2: "veldr.element.ui.generic.icons.skull_2",
        fireplace: "veldr.element.ui.generic.fireplace",

        // Crosshair
        crosshair_inner: "veldr.element.ui.settings.icons.crosshair_inner",

        crosshair_outer_round: "veldr.element.ui.settings.icons.crosshair_outer_1",
        crosshair_outer_round_edges: "veldr.element.ui.settings.icons.crosshair_outer_2",
        crosshair_outer_edges: "veldr.element.ui.settings.icons.crosshair_outer_3",

        crosshair_bg: "veldr.element.ui.settings.icons.crosshair_bg",
        crosshair_bg_hover: "veldr.element.ui.settings.icons.crosshair_bg_hover",
        crosshair_bg_press: "veldr.element.ui.settings.icons.crosshair_bg_press",
        crosshair_bg_pressed: "veldr.element.ui.settings.icons.crosshair_bg_pressed",

        crosshair_charge_0: "veldr.element.animation.crosshair_charge.charge_0",
        crosshair_charge_1: "veldr.element.animation.crosshair_charge.charge_1",
        crosshair_charge_2: "veldr.element.animation.crosshair_charge.charge_2",
        crosshair_charge_3: "veldr.element.animation.crosshair_charge.charge_3",
        crosshair_charge_4: "veldr.element.animation.crosshair_charge.charge_4",
        crosshair_charge_5: "veldr.element.animation.crosshair_charge.charge_5",
        crosshair_charge_6: "veldr.element.animation.crosshair_charge.charge_6",
        crosshair_charge_7: "veldr.element.animation.crosshair_charge.charge_7",
        crosshair_charge_8: "veldr.element.animation.crosshair_charge.charge_8",

        // Map
        map_topo: "veldr.element.ui.map.buttons.topographic",
        map_bg: "veldr.element.ui.map.map_bg",
        map_frame: "veldr.element.ui.map.map_frame",
        map_frame_art: "veldr.element.ui.map.map_frame_art",
        view_mmap: "veldr.element.ui.minimap.icons.mmap_view",
        indicator_mmap: "veldr.element.ui.minimap.icons.indicator_mmap",
        indicator_mmap_colored: "veldr.element.ui.minimap.icons.indicator_mmap_colored",
        indicator_map_overlay: "veldr.element.ui.minimap.icons.indicator_mmap_small",
        indicator_group: "veldr.element.ui.map.buttons.group_indicator",
        indicator_group_up: "veldr.element.ui.map.buttons.group_indicator_arrow_up",
        indicator_group_down: "veldr.element.ui.map.buttons.group_indicator_arrow_down",
        location_marker: "veldr.element.ui.map.buttons.location_marker",
        location_marker_group: "veldr.element.ui.map.buttons.location_marker_group",
        location_marker_group_leader: "veldr.element.ui.map.buttons.location_marker_group_leader",
        map_mode_overlay: "veldr.element.ui.map.buttons.map_modes",
        minimap_mode_overlay: "veldr.element.ui.map.buttons.minimap_modes",

        // MiniMap
        mmap_frame: "veldr.element.ui.minimap.mmap",
        mmap_frame_2: "veldr.element.ui.minimap.mmap_frame",
        mmap_frame_closed: "veldr.element.ui.minimap.mmap_closed",
        mmap_closed: "veldr.element.ui.minimap.buttons.button_mmap_closed",
        mmap_closed_hover: "veldr.element.ui.minimap.buttons.button_mmap_closed_hover",
        mmap_closed_press: "veldr.element.ui.minimap.buttons.button_mmap_closed_press",
        mmap_open: "veldr.element.ui.minimap.buttons.button_mmap_open",
        mmap_open_hover: "veldr.element.ui.minimap.buttons.button_mmap_open_hover",
        mmap_open_press: "veldr.element.ui.minimap.buttons.button_mmap_open_press",
        mmap_plus: "veldr.element.ui.minimap.buttons.mmap_button-plus",
        mmap_plus_hover: "veldr.element.ui.minimap.buttons.mmap_button-plus_hover",
        mmap_plus_press: "veldr.element.ui.minimap.buttons.mmap_button-plus_press",
        mmap_minus: "veldr.element.ui.minimap.buttons.mmap_button-min",
        mmap_minus_hover: "veldr.element.ui.minimap.buttons.mmap_button-min_hover",
        mmap_minus_press: "veldr.element.ui.minimap.buttons.mmap_button-min_press",
        mmap_north: "veldr.element.ui.minimap.buttons.mmap_button-north",
        mmap_north_hover: "veldr.element.ui.minimap.buttons.mmap_button-north_hover",
        mmap_north_press: "veldr.element.ui.minimap.buttons.mmap_button-north_press",
        mmap_north_press_hover: "veldr.element.ui.minimap.buttons.mmap_button-north_press_hover",
        map_dif_1: "veldr.element.ui.map.icons.dif_1",
        map_dif_2: "veldr.element.ui.map.icons.dif_2",
        map_dif_3: "veldr.element.ui.map.icons.dif_3",
        map_dif_4: "veldr.element.ui.map.icons.dif_4",
        map_dif_5: "veldr.element.ui.map.icons.dif_5",
        map_dif_6: "veldr.element.ui.map.icons.dif_6",
        map_dif_icon: "veldr.element.ui.map.icons.dif_map_icon",
        map_dif_unknown: "veldr.element.ui.map.icons.dif_unknown",
        mmap_unknown: "veldr.element.ui.map.buttons.unknown",
        mmap_unknown_hover: "veldr.element.ui.map.buttons.unknown_hover",
        mmap_unknown_bg: "veldr.element.ui.map.buttons.unknown_bg",
        mmap_character: "veldr.element.ui.map.buttons.character",
        mmap_character_hover: "veldr.element.ui.map.buttons.character_hover",
        mmap_site_town: "veldr.element.ui.map.buttons.town",
        mmap_site_town_hover: "veldr.element.ui.map.buttons.town_hover",
        mmap_site_town_bg: "veldr.element.ui.map.buttons.town_bg",
        mmap_site_sea_chapel_hover: "veldr.element.ui.map.buttons.sea_chapel_hover",
        mmap_site_sea_chapel_bg: "veldr.element.ui.map.buttons.sea_chapel_bg",
        mmap_site_sea_chapel: "veldr.element.ui.map.buttons.sea_chapel",
        mmap_site_terracotta_hover: "veldr.element.ui.map.buttons.terracotta_hover",
        mmap_site_terracotta_bg: "veldr.element.ui.map.buttons.terracotta_bg",
        mmap_site_terracotta: "veldr.element.ui.map.buttons.terracotta",
        mmap_site_dungeon: "veldr.element.ui.map.buttons.dungeon",
        mmap_site_dungeon_hover: "veldr.element.ui.map.buttons.dungeon_hover",
        mmap_site_dungeon_bg: "veldr.element.ui.map.buttons.dungeon_bg",
        mmap_site_castle: "veldr.element.ui.map.buttons.castle",
        mmap_site_castle_hover: "veldr.element.ui.map.buttons.castle_hover",
        mmap_site_castle_bg: "veldr.element.ui.map.buttons.castle_bg",
        mmap_site_bridge: "veldr.element.ui.map.buttons.bridge",
        mmap_site_bridge_hover: "veldr.element.ui.map.buttons.bridge_hover",
        mmap_site_bridge_bg: "veldr.element.ui.map.buttons.bridge_bg",
        mmap_site_glider_course: "veldr.element.ui.map.buttons.glider_course",
        mmap_site_glider_course_hover: "veldr.element.ui.map.buttons.glider_course_hover",
        mmap_site_glider_course_bg: "veldr.element.ui.map.buttons.glider_course_bg",
        mmap_site_cave_bg: "veldr.element.ui.map.buttons.cave_bg",
        mmap_site_cave_hover: "veldr.element.ui.map.buttons.cave_hover",
        mmap_site_cave: "veldr.element.ui.map.buttons.cave",
        mmap_site_excl: "veldr.element.ui.map.buttons.excl",
        mmap_site_tree: "veldr.element.ui.map.buttons.tree",
        mmap_site_tree_hover: "veldr.element.ui.map.buttons.tree_hover",
        mmap_poi_peak: "veldr.element.ui.map.buttons.peak",
        mmap_poi_biome: "veldr.element.ui.map.buttons.biome",
        mmap_poi_peak_hover: "veldr.element.ui.map.buttons.peak_hover",
        mmap_site_gnarling: "veldr.element.ui.map.buttons.gnarling",
        mmap_site_gnarling_hover: "veldr.element.ui.map.buttons.gnarling_hover",
        mmap_site_gnarling_bg: "veldr.element.ui.map.buttons.gnarling_bg",
        mmap_site_adlet: "veldr.element.ui.map.buttons.adlet",
        mmap_site_adlet_hover: "veldr.element.ui.map.buttons.adlet_hover",
        mmap_site_adlet_bg: "veldr.element.ui.map.buttons.adlet_bg",
        mmap_site_haniwa: "veldr.element.ui.map.buttons.haniwa",
        mmap_site_haniwa_hover: "veldr.element.ui.map.buttons.haniwa_hover",
        mmap_site_haniwa_bg: "veldr.element.ui.map.buttons.haniwa_bg",
        mmap_site_cultist: "veldr.element.ui.map.buttons.mindflayer",
        mmap_site_cultist_hover: "veldr.element.ui.map.buttons.mindflayer_hover",
        mmap_site_cultist_bg: "veldr.element.ui.map.buttons.mindflayer_bg",
        mmap_site_sahagin: "veldr.element.ui.map.buttons.tidal_warrior",
        mmap_site_sahagin_hover: "veldr.element.ui.map.buttons.tidal_warrior_hover",
        mmap_site_sahagin_bg: "veldr.element.ui.map.buttons.tidal_warrior_bg",
        mmap_site_myrmidon: "veldr.element.ui.map.buttons.minotaur",
        mmap_site_myrmidon_hover: "veldr.element.ui.map.buttons.minotaur_hover",
        mmap_site_myrmidon_bg: "veldr.element.ui.map.buttons.minotaur_bg",
        mmap_site_mindflayer: "veldr.element.ui.map.buttons.mindflayer",
        mmap_site_mindflayer_hover: "veldr.element.ui.map.buttons.mindflayer_hover",
        mmap_site_mindflayer_bg: "veldr.element.ui.map.buttons.mindflayer_bg",
        mmap_site_mine: "veldr.element.ui.map.buttons.mine",
        mmap_site_mine_hover: "veldr.element.ui.map.buttons.mine_hover",
        mmap_site_mine_bg: "veldr.element.ui.map.buttons.mine_bg",
        mmap_site_vampire_castle_hover: "veldr.element.ui.map.buttons.bloodmoon_heiress_hover",
        mmap_site_vampire_castle_bg: "veldr.element.ui.map.buttons.bloodmoon_heiress_bg",
        mmap_site_vampire_castle: "veldr.element.ui.map.buttons.bloodmoon_heiress",

        // Window Parts
        window_3: "veldr.element.ui.generic.frames.window_3",
        esc_frame: "veldr.element.ui.generic.frames.esc_menu",
        // Settings
        settings_bg: "veldr.element.ui.settings.settings_bg",
        settings_frame: "veldr.element.ui.settings.settings_frame",

        // Close-Button
        close_btn: "veldr.element.ui.generic.buttons.close_btn",
        close_btn_hover: "veldr.element.ui.generic.buttons.close_btn_hover",
        close_btn_press: "veldr.element.ui.generic.buttons.close_btn_press",
        close_button: "veldr.element.ui.generic.buttons.close_btn",
        close_button_hover: "veldr.element.ui.generic.buttons.close_btn_hover",
        close_button_press: "veldr.element.ui.generic.buttons.close_btn_press",

        // Search-button
        search_btn: "veldr.element.ui.generic.buttons.search_btn",
        search_btn_hover: "veldr.element.ui.generic.buttons.search_btn_hover",
        search_btn_press: "veldr.element.ui.generic.buttons.search_btn_press",

        // Eye-buttons
        eye_open_btn: "veldr.element.ui.generic.buttons.eye_open_btn",
        eye_open_btn_hover: "veldr.element.ui.generic.buttons.eye_open_btn_hover",
        eye_open_btn_press: "veldr.element.ui.generic.buttons.eye_open_btn_press",
        eye_closed_btn: "veldr.element.ui.generic.buttons.eye_closed_btn",
        eye_closed_btn_hover: "veldr.element.ui.generic.buttons.eye_closed_btn_hover",
        eye_closed_btn_press: "veldr.element.ui.generic.buttons.eye_closed_btn_press",

        // Edit-Button
        edit_btn: "veldr.element.ui.char_select.icons.pen",
        edit_btn_hover: "veldr.element.ui.char_select.icons.pen_hover",
        edit_btn_press: "veldr.element.ui.char_select.icons.pen_press",

        // Disable bell button
        disable_bell_btn: "veldr.element.ui.generic.buttons.disable_bell_btn",

        // Inventory
        grid_btn: "veldr.element.ui.bag.buttons.inv_grid",
        grid_btn_hover: "veldr.element.ui.bag.buttons.inv_grid_hover",
        grid_btn_press: "veldr.element.ui.bag.buttons.inv_grid_press",
        list_btn: "veldr.element.ui.bag.buttons.inv_list",
        list_btn_hover: "veldr.element.ui.bag.buttons.inv_list_hover",
        list_btn_press: "veldr.element.ui.bag.buttons.inv_list_press",
        collapse_btn: "veldr.element.ui.bag.buttons.inv_collapse",
        collapse_btn_hover: "veldr.element.ui.bag.buttons.inv_collapse_hover",
        collapse_btn_press: "veldr.element.ui.bag.buttons.inv_collapse_press",
        expand_btn: "veldr.element.ui.bag.buttons.inv_expand",
        expand_btn_hover: "veldr.element.ui.bag.buttons.inv_expand_hover",
        expand_btn_press: "veldr.element.ui.bag.buttons.inv_expand_press",
        inv_sort_btn: "veldr.element.ui.bag.buttons.inv_sort",
        inv_sort_btn_hover: "veldr.element.ui.bag.buttons.inv_sort_hover",
        inv_sort_btn_press: "veldr.element.ui.bag.buttons.inv_sort_press",
        inv_sort_selected_btn: "veldr.element.ui.bag.buttons.inv_sort_selected",
        inv_sort_selected_btn_hover: "veldr.element.ui.bag.buttons.inv_sort_selected_hover",
        inv_sort_selected_btn_press: "veldr.element.ui.bag.buttons.inv_sort_selected_press",
        swap_equipped_weapons_btn: "veldr.element.ui.bag.buttons.swap_equipped_weapons",
        swap_equipped_weapons_btn_hover: "veldr.element.ui.bag.buttons.swap_equipped_weapons_hover",
        swap_equipped_weapons_btn_press: "veldr.element.ui.bag.buttons.swap_equipped_weapons_press",
        inv_bg_armor: "veldr.element.ui.bag.inv_bg_0",
        inv_bg_stats: "veldr.element.ui.bag.inv_bg_1",
        inv_frame: "veldr.element.ui.bag.inv_frame",
        inv_frame_bag: "veldr.element.ui.bag.inv_frame_bag",
        inv_bg_bag: "veldr.element.ui.bag.inv_bg_bag",
        player_inv_frame_bag: "veldr.element.ui.bag.player_inv_frame_bag",
        player_inv_bg_bag: "veldr.element.ui.bag.player_inv_bg_bag",
        inv_middle_bg_bag: "veldr.element.ui.bag.inv_middle_bg_bag",
        inv_middle_frame: "veldr.element.ui.bag.inv_middle_frame",
        char_art: "veldr.element.ui.bag.icons.character",
        inv_slot: "veldr.element.ui.bag.buttons.inv_slot",
        inv_slot_grey: "veldr.element.ui.bag.buttons.inv_slot_grey",
        inv_slot_common: "veldr.element.ui.bag.buttons.inv_slot_common",
        inv_slot_green: "veldr.element.ui.bag.buttons.inv_slot_green",
        inv_slot_blue: "veldr.element.ui.bag.buttons.inv_slot_blue",
        inv_slot_purple: "veldr.element.ui.bag.buttons.inv_slot_purple",
        inv_slot_gold: "veldr.element.ui.bag.buttons.inv_slot_gold",
        inv_slot_orange: "veldr.element.ui.bag.buttons.inv_slot_orange",
        inv_slot_red: "veldr.element.ui.bag.buttons.inv_slot_red",
        inv_slot_sel: "veldr.element.ui.bag.buttons.inv_slot_sel",
        scrollbar_bg: "veldr.element.ui.generic.slider.scrollbar",
        scrollbar_bg_big: "veldr.element.ui.generic.slider.scrollbar_1",
        second_phase_scrollbar_bg: "veldr.element.ui.bag.second_phase_scrollbar_bg",
        inv_tab_active: "veldr.element.ui.bag.buttons.inv_tab_active",
        inv_tab_inactive: "veldr.element.ui.bag.buttons.inv_tab_inactive",
        inv_tab_inactive_hover: "veldr.element.ui.bag.buttons.inv_tab_inactive",
        inv_tab_inactive_press: "veldr.element.ui.bag.buttons.inv_tab_inactive",
        armor_slot: "veldr.element.ui.generic.buttons.armor_slot",
        armor_slot_sel: "veldr.element.ui.generic.buttons.armor_slot_selected",
        armor_slot_empty: "veldr.element.ui.generic.buttons.armor_slot_empty",
        head_bg: "veldr.element.ui.bag.backgrounds.head",
        shoulders_bg: "veldr.element.ui.bag.backgrounds.shoulders",
        hands_bg: "veldr.element.ui.bag.backgrounds.hands",
        belt_bg: "veldr.element.ui.bag.backgrounds.belt",
        legs_bg: "veldr.element.ui.bag.backgrounds.legs",
        feet_bg: "veldr.element.ui.bag.backgrounds.feet",
        ring_bg: "veldr.element.ui.bag.backgrounds.ring",
        tabard_bg: "veldr.element.ui.bag.backgrounds.tabard",
        glider_bg: "veldr.element.ui.bag.backgrounds.glider",
        chest_bg: "veldr.element.ui.bag.backgrounds.chest",
        back_bg: "veldr.element.ui.bag.backgrounds.back",
        lantern_bg: "veldr.element.ui.bag.backgrounds.lantern",
        necklace_bg: "veldr.element.ui.bag.backgrounds.necklace",
        mainhand_bg: "veldr.element.ui.bag.backgrounds.mainhand",
        bag_bg: "veldr.element.ui.bag.backgrounds.bag",
        offhand_bg: "veldr.element.ui.bag.backgrounds.offhand",
        energy_ico: "veldr.element.ui.bag.icons.energy",
        health_ico: "veldr.element.ui.bag.icons.health",
        protection_ico: "veldr.element.ui.bag.icons.protection",
        stun_res_ico: "veldr.element.ui.bag.icons.stun_res",
        combat_rating_ico: "veldr.element.ui.bag.icons.combat_rating",
        combat_rating_ico_shadow: "veldr.element.ui.bag.icons.combat_rating_shadow",
        stealth_rating_ico: "veldr.element.ui.bag.icons.stealth_rating",

        not_found: "veldr.element.not_found",

        death_bg: "veldr.background.death",
        hurt_bg: "veldr.background.hurt",

        banner_top: "veldr.element.ui.generic.frames.banner_top",

        // Icons
        snake_arrow_0: "veldr.element.skills.snake",
        skill_sceptre_lifesteal: "veldr.element.skills.lifesteal",
        skill_sceptre_heal: "veldr.element.skills.heal_aoe",
        skill_sceptre_aura: "veldr.element.skills.sceptre_protection",
        instrument: "veldr.element.skills.music",

        // Buttons
        button: "veldr.element.ui.generic.buttons.button",
        button_hover: "veldr.element.ui.generic.buttons.button_hover",
        button_press: "veldr.element.ui.generic.buttons.button_press",

        // Mute Buttons
        button_mute: "veldr.element.ui.generic.buttons.mute_btn",
        button_mute_hover: "veldr.element.ui.generic.buttons.mute_btn_hover",
        button_mute_press: "veldr.element.ui.generic.buttons.mute_btn_press",
        button_muted: "veldr.element.ui.generic.buttons.muted_btn",
        button_muted_hover: "veldr.element.ui.generic.buttons.muted_btn_hover",
        button_muted_press: "veldr.element.ui.generic.buttons.muted_btn_press",


        // Enemy Healthbar
        enemy_health: "veldr.element.ui.generic.frames.enemybar",
        enemy_health_bg: "veldr.element.ui.generic.frames.enemybar_bg",
        health_bar_group: "veldr.element.ui.generic.frames.enemybar_1",
        health_bar_group_bg: "veldr.element.ui.generic.frames.enemybar_bg_1",
        // Enemy Bar Content:
        enemy_bar: "veldr.element.ui.skillbar.enemy_bar_content",
        map_icon: "veldr.element.ui.generic.buttons.map",
        grid_button: "veldr.element.ui.generic.buttons.border",
        grid_button_hover: "veldr.element.ui.generic.buttons.border_mo",
        grid_button_press: "veldr.element.ui.generic.buttons.border_press",
        grid_button_open: "veldr.element.ui.generic.buttons.border_pressed",

        // Char Window
        progress_frame: "veldr.element.ui.invite.progress_bar",
        progress: "veldr.element.ui.invite.progress",

        // Speech bubbles
        speech_bubble_top_left: "veldr.element.ui.generic.frames.bubble.top_left",
        speech_bubble_top: "veldr.element.ui.generic.frames.bubble.top",
        speech_bubble_top_right: "veldr.element.ui.generic.frames.bubble.top_right",
        speech_bubble_left: "veldr.element.ui.generic.frames.bubble.left",
        speech_bubble_mid: "veldr.element.ui.generic.frames.bubble.mid",
        speech_bubble_right: "veldr.element.ui.generic.frames.bubble.right",
        speech_bubble_bottom_left: "veldr.element.ui.generic.frames.bubble.bottom_left",
        speech_bubble_bottom: "veldr.element.ui.generic.frames.bubble.bottom",
        speech_bubble_bottom_right: "veldr.element.ui.generic.frames.bubble.bottom_right",
        speech_bubble_tail: "veldr.element.ui.generic.frames.bubble.tail",
        speech_bubble_icon_frame: "veldr.element.ui.generic.frames.bubble_dark.icon_frame",

        dark_bubble_top_left: "veldr.element.ui.generic.frames.bubble_dark.top_left",
        dark_bubble_top: "veldr.element.ui.generic.frames.bubble_dark.top",
        dark_bubble_top_right: "veldr.element.ui.generic.frames.bubble_dark.top_right",
        dark_bubble_left: "veldr.element.ui.generic.frames.bubble_dark.left",
        dark_bubble_mid: "veldr.element.ui.generic.frames.bubble_dark.mid",
        dark_bubble_right: "veldr.element.ui.generic.frames.bubble_dark.right",
        dark_bubble_bottom_left: "veldr.element.ui.generic.frames.bubble_dark.bottom_left",
        dark_bubble_bottom: "veldr.element.ui.generic.frames.bubble_dark.bottom",
        dark_bubble_bottom_right: "veldr.element.ui.generic.frames.bubble_dark.bottom_right",
        dark_bubble_tail: "veldr.element.ui.generic.frames.bubble_dark.tail",
        dark_bubble_icon_frame: "veldr.element.ui.generic.frames.bubble_dark.icon_frame",


        // Chat icons
        chat_faction_small: "veldr.element.ui.chat.icons.faction_small",
        chat_group_small: "veldr.element.ui.chat.icons.group_small",
        chat_kill_small: "veldr.element.ui.chat.icons.kill_small",
        chat_region_small: "veldr.element.ui.chat.icons.region_small",
        chat_say_small: "veldr.element.ui.chat.icons.say_small",
        chat_tell_small: "veldr.element.ui.chat.icons.tell_small",
        chat_world_small: "veldr.element.ui.chat.icons.world_small",
        chat_command_error_small: "veldr.element.ui.chat.icons.command_error_small",
        chat_command_info_small: "veldr.element.ui.chat.icons.command_info_small",
        chat_online_small: "veldr.element.ui.chat.icons.online_small",
        chat_offline_small: "veldr.element.ui.chat.icons.offline_small",

        chat_faction: "veldr.element.ui.chat.icons.faction",
        chat_group: "veldr.element.ui.chat.icons.group",
        chat_region: "veldr.element.ui.chat.icons.region",
        chat_say: "veldr.element.ui.chat.icons.say",
        chat_tell: "veldr.element.ui.chat.icons.tell",
        chat_world: "veldr.element.ui.chat.icons.world",

        chat_moderator_badge: "veldr.element.ui.chat.icons.mod_badge",

        // Buffs
        buff_plus_0: "veldr.element.de_buffs.buff_plus_0",
        buff_saturation_0: "veldr.element.de_buffs.buff_saturation_0",
        buff_potion_0: "veldr.element.de_buffs.buff_potion_0",
        // TODO Change buff image name
        buff_resting_heal_0: "veldr.element.de_buffs.buff_campfire_heal_0",
        buff_energyplus_0: "veldr.element.de_buffs.buff_energyplus_0",
        buff_healthplus_0: "veldr.element.de_buffs.buff_healthplus_0",
        buff_invincibility_0: "veldr.element.de_buffs.buff_invincibility_0",
        buff_dmg_red_0: "veldr.element.de_buffs.buff_damage_reduce_0",
        buff_frenzy_0: "veldr.element.de_buffs.buff_frenzy_0",
        buff_haste_0: "veldr.element.de_buffs.buff_haste_0",
        buff_fortitude_0: "veldr.element.de_buffs.buff_fortitude_0",
        buff_reckless: "veldr.element.de_buffs.buff_reckless",
        buff_imminentcritical: "veldr.element.de_buffs.buff_imminentcritical",
        buff_fury: "veldr.element.de_buffs.buff_fury",
        buff_sunderer: "veldr.element.de_buffs.buff_sunderer",
        buff_defiance: "veldr.element.de_buffs.buff_defiance",
        buff_lifesteal: "veldr.element.de_buffs.buff_lifesteal",
        buff_flame: "veldr.element.de_buffs.buff_flame",
        buff_frigid: "veldr.element.de_buffs.buff_frigid",
        buff_scornfultaunt: "veldr.element.de_buffs.buff_scornfultaunt",
        buff_tenacity: "veldr.element.de_buffs.buff_tenacity",
        buff_resilience: "veldr.element.de_buffs.buff_resilience",
        buff_owltalon: "veldr.element.de_buffs.buff_owltalon",
        buff_heavynock: "veldr.element.de_buffs.buff_heavynock",
        buff_heartseeker: "veldr.element.de_buffs.buff_heartseeker",
        buff_eagleeye: "veldr.element.de_buffs.buff_eagleeye",
        buff_ardenthunter: "veldr.element.de_buffs.buff_ardenthunter",
        buff_septicshot: "veldr.element.de_buffs.buff_septicshot",

        // Debuffs
        debuff_cursed_0: "veldr.element.de_buffs.debuff_cursed_0",
        debuff_bleed_0: "veldr.element.de_buffs.debuff_bleed_0",
        debuff_burning_0: "veldr.element.de_buffs.debuff_burning_0",
        debuff_crippled_0: "veldr.element.de_buffs.debuff_cripple_0",
        debuff_frozen_0: "veldr.element.de_buffs.debuff_frozen_0",
        debuff_wet_0: "veldr.element.de_buffs.debuff_wet_0",
        debuff_ensnared_0: "veldr.element.de_buffs.debuff_ensnared_0",
        debuff_poisoned_0: "veldr.element.de_buffs.debuff_poisoned_0",
        debuff_parried_0: "veldr.element.de_buffs.debuff_parried_0",
        debuff_potionsickness_0: "veldr.element.de_buffs.debuff_potionsickness_0",
        debuff_polymorphed_0: "veldr.element.de_buffs.debuff_polymorphed_0",
        debuff_heatstroke_0: "veldr.element.de_buffs.debuff_heatstroke_0",
        debuff_rooted_0: "veldr.element.de_buffs.debuff_rooted_0",
        debuff_winded_0: "veldr.element.de_buffs.debuff_winded_0",
        debuff_amnesia_0: "veldr.element.de_buffs.debuff_amnesia_0",
        debuff_offbalance_0: "veldr.element.de_buffs.debuff_offbalance_0",
        debuff_chilled: "veldr.element.de_buffs.debuff_chilled",
        debuff_ardenthunted: "veldr.element.de_buffs.debuff_ardenthunted",

        // Animation Frames
        // Buff Frame
        buff_0: "veldr.element.animation.buff_frame.1",
        buff_1: "veldr.element.animation.buff_frame.2",
        buff_2: "veldr.element.animation.buff_frame.3",
        buff_3: "veldr.element.animation.buff_frame.4",
        buff_4: "veldr.element.animation.buff_frame.5",
        buff_5: "veldr.element.animation.buff_frame.6",
        buff_6: "veldr.element.animation.buff_frame.7",
        buff_7: "veldr.element.animation.buff_frame.8",

        <BlankGraphic>
        nothing: (),
    }
}
